(package "ert-font-lock"
         "0.1.0"
         "ERT Font Lock")

(license "GPLv3")
(website-url "https://github.com/vkazanov/ert-font-lock")
(keywords "lisp" "test")

(package-file "ert-font-lock.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "29.1")
(development
 (depends-on "ert-runner")
 (depends-on "elisp-lint")
 (depends-on "php-mode"))
